apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ .Values.appName }}-dr
  namespace: {{ .Values.namespace }}
spec:
  host: {{ .Values.appName }}-svc
  subsets:
    - name: stable
      labels:
        app: {{ .Values.appName }}
    - name: preview
      labels:
        app: {{ .Values.appName }}
