apiVersion: v1
kind: Pod
metadata:
  name: eks-irsa-test2
  labels:
    app: irsa-pod
spec:
  serviceAccountName: pod-identity-sa
  containers:
  - name: eks-irsa-test2
    image: amazon/aws-cli:latest
    command: ["sleep"]
    args: ["3600"]
    resources:
      requests:
        cpu: 0.5
        memory: 300Mi
      limits:
        cpu: 0.5
        memory: 300Mi
  restartPolicy: Never
