apiVersion: v1
kind: Pod
metadata:
  name: netshoot
  labels:
    app: netshoot
spec:
  containers:
  - name: my-shell-hostnet
    image: nicolaka/netshoot
    args:
    - sleep
    - infinity
    resources:
      requests:
        cpu: 0.5
        memory: 300Mi
      limits:
        cpu: 0.5
        memory: 300Mi

