apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: {{ .Values.appName }}-analysis
  namespace: {{ .Values.namespace }}
spec:
  # this analysis template requires a service name and namespace to be supplied to the query
  args:
    - name: service
    - name: namespace
  metrics:
    {{- toYaml .Values.canary.analysis.metrics | nindent 4 }}
