apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: istio-gateway
  namespace: {{ .Values.namespace }}
spec:
  selector:
    istio: ingressgateway
  servers:
    - hosts:
      - {{ .Values.host }}
      port:
        number: 80
        name: http
        protocol: HTTP
      