### external to service
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.appName }}-vsvc
  namespace: {{ .Values.namespace }}
spec:
  hosts:
    - {{ .Values.host }}
  gateways:
    - {{ .Values.namespace }}/istio-gateway
  http:
    - name: http-primary
      route:
      - destination:
          host: {{ .Values.appName }}-svc
          subset: stable
        weight: 100
      - destination:
          host: {{ .Values.appName }}-svc
          subset: preview
        weight: 0
