apiVersion: v1
kind: Pod
metadata:
  name: pod-https
  namespace: {your-name}
  labels:
    app: https
spec:
  containers:
  - name: container
    image: k8s.gcr.io/echoserver:1.6
  terminationGracePeriodSeconds: 0
