name: Docker build and push

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'tag'
        required: true

permissions:
  packages: write
  contents: write
  id-token: write
  actions: read

env:
  AWS_ROLE_NAME: arn:aws:iam::467606240901:role/github-actions-education
  AWS_REGION: ap-northeast-2
  ECR_REGISTRY: 467606240901.dkr.ecr.ap-northeast-2.amazonaws.com
jobs:
  docker_build_and_push:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: ${{ env.AWS_REGION }}
        role-to-assume: ${{ env.AWS_ROLE_NAME }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      with:
        registries: "467606240901"

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ env.ECR_REGISTRY }}
        IMAGE_TAG: ${{ inputs.tag }}
      run: |
        cd cicd_example
        docker build -t $ECR_REGISTRY/education:${{ inputs.tag }} .
        docker push $ECR_REGISTRY/education:${{ inputs.tag }}

    - name: Change Image tag
      run: |
        cd cicd_example/manifests
        yq eval '.spec.template.spec.containers[0].image = "467606240901.dkr.ecr.ap-northeast-2.amazonaws.com/education:${{ inputs.tag }}"' deployment.yaml > deployment.yaml

    - name: GIT commit and push docs
      env:
        CI_COMMIT_MESSAGE: Update Tag - ${{ inputs.tag }}
        CI_COMMIT_AUTHOR: testuser
      run: |
        git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
        git config --global user.email "testuser"
        git status
        git add -A
        git commit -m "${{ env.CI_COMMIT_MESSAGE }}"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
